"""Turn a successful modernization's verification exhaust — the baseline
stdout and probes that already PROVED this chunk's behavior didn't
change — into a durable, standalone test file written into the target
repo, so re-checking that behavior later never needs another LLM call or
this project at all.

Scoped to the 4 languages that generate probes in the first place
(python/javascript/typescript/php — see agents/nodes.py's
supports_function_probe): C++/Java chunks never have probe data to turn
into anything, so there's nothing language-specific to build for them.

Each generated test EMBEDS the modernized function's source directly
rather than importing it from the original file. Deliberate trade-off:
an imported/live version would catch future regressions if someone
edits the original file later, but reliably importing a specific
function from an ARBITRARY legacy file (which may have no module-export
convention at all — plenty of legacy scripts are just top-level
functions plus a few bare calls, exactly the shape this project targets)
is fragile to get right generically across 4 languages. An embedded,
self-contained test is simple, always runnable regardless of the
target's file structure, and still delivers real value: a permanent,
versioned, diffable record of verified behavior for these specific
inputs, runnable in CI without this project or an LLM in the loop.

Every generated test re-derives its check the EXACT same way this
project's own sandbox verification does — run the probe snippet, capture
its printed output, compare against the recorded baseline — rather than
attempting a traditional `assert func(x) == y` form. Probe snippets are
already complete print/console.log/echo STATEMENTS (see
agents/nodes.py's _PROBE_WRAPPERS), not bare expressions, so this is the
form that requires no re-parsing and stays faithful to what was actually
verified.
"""
import json


def _php_string_literal(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def regression_test_filename(language: str, original_file_path: str) -> str:
    """e.g. calc.py -> test_calc_modernized.py. A NEW sibling file, same
    non-destructive convention as the .modernized.<ext> output itself —
    never overwrites anything, including a pre-existing test file with
    the same base name (the _modernized suffix avoids that collision)."""
    import os
    directory, filename = os.path.split(original_file_path)
    stem, ext = os.path.splitext(filename)
    if language == "python":
        return os.path.join(directory, f"test_{stem}_modernized.py")
    if language in ("javascript", "typescript"):
        return os.path.join(directory, f"{stem}.modernized.test{ext}")
    if language == "php":
        return os.path.join(directory, f"{stem}ModernizedTest.php")
    raise ValueError(f"regression tests not supported for language: {language}")


def _generate_python_test(chunk_results: list[dict]) -> str:
    functions = "\n\n".join(c["modernized_code"] for c in chunk_results)
    tests = []
    i = 0
    for chunk in chunk_results:
        for probe in chunk["probes"]:
            tests.append(f'''    def test_probe_{i}(self):
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            {probe["snippet"]}
        self.assertEqual(buf.getvalue(), {probe["baseline_stdout"]!r})''')
            i += 1
    return f'''"""Auto-generated by code-modernizer from verification probes captured
during modernization — see regression_tests.py. Safe to keep, edit, or
delete; re-running the modernizer will not overwrite this file."""
import contextlib
import io
import unittest

{functions}


class TestModernizedRegressions(unittest.TestCase):
{chr(10).join(tests)}


if __name__ == "__main__":
    unittest.main()
'''


def _generate_js_test(chunk_results: list[dict], typescript: bool) -> str:
    functions = "\n\n".join(c["modernized_code"] for c in chunk_results)
    tests = []
    i = 0
    for chunk in chunk_results:
        for probe in chunk["probes"]:
            # The snippet gets its OWN line, with the closing braces on
            # separate lines below — never appended after it on the same
            # line. Probe snippets sometimes carry a trailing `//`
            # comment despite being told not to (confirmed live: the
            # model produced "console.log(add(2, 3)); // 5"), and `//`
            # comments out everything after it on that line — including
            # a same-line closing brace, corrupting the whole file with
            # an unterminated block. Multi-line embedding makes that
            # class of bug structurally impossible regardless of what a
            # snippet contains.
            tests.append(f'''test("probe_{i}", () => {{
  const output = _captureStdout(() => {{
    {probe["snippet"]}
  }});
  assert.strictEqual(output, {json.dumps(probe["baseline_stdout"])});
}});''')
            i += 1

    # TS-only bits, built as separate strings rather than generating one
    # shared template and stripping type annotations afterward — a
    # blanket string-replace on the finished file could corrupt embedded
    # user code that happens to contain the same substrings (a comment,
    # a string literal) for unrelated reasons.
    declare_require = (
        "declare function require(name: string): any;\ndeclare const process: any;\n" if typescript else ""
    )
    fn_param_type = ": any" if typescript else ""
    fn_return_type = ": string" if typescript else ""
    chunk_param_type = ": any" if typescript else ""
    test_fn_type = ": string, fn: () => void" if typescript else ", fn"
    catch_type = ": any" if typescript else ""
    void_return = ": void" if typescript else ""

    return f'''// Auto-generated by code-modernizer from verification probes captured
// during modernization — see regression_tests.py. Safe to keep, edit,
// or delete; re-running the modernizer will not overwrite this file.
{declare_require}const assert = require("node:assert");

{functions}

function _captureStdout(fn{fn_param_type}){fn_return_type} {{
  const originalWrite = process.stdout.write.bind(process.stdout);
  let captured = "";
  process.stdout.write = (chunk{chunk_param_type}) => {{ captured += chunk; return true; }};
  try {{
    fn();
  }} finally {{
    process.stdout.write = originalWrite;
  }}
  return captured;
}}

let failures = 0;

function test(name{test_fn_type}){void_return} {{
  try {{
    fn();
    console.log(`PASS: ${{name}}`);
  }} catch (e{catch_type}) {{
    failures++;
    console.log(`FAIL: ${{name}}: ${{e.message}}`);
  }}
}}

{chr(10).join(tests)}

process.exit(failures > 0 ? 1 : 0);
'''


def _generate_php_test(chunk_results: list[dict]) -> str:
    functions = "\n\n".join(c["modernized_code"] for c in chunk_results)
    checks = []
    i = 0
    for chunk in chunk_results:
        for probe in chunk["probes"]:
            # Snippet on its own line, closing tokens below — see the JS
            # generator's comment for why: a probe snippet with a
            # trailing `//` comment (the model doesn't always follow
            # "nothing else on that line") would otherwise swallow
            # anything appended after it on the same line, including the
            # closing braces/parens that finish this statement.
            checks.append(
                f'_check("probe_{i}", _capture(function() {{\n'
                f'    {probe["snippet"]}\n'
                f'}}), {_php_string_literal(probe["baseline_stdout"])});'
            )
            i += 1
    return f'''<?php
// Auto-generated by code-modernizer from verification probes captured
// during modernization — see regression_tests.py. Safe to keep, edit,
// or delete; re-running the modernizer will not overwrite this file.

{functions}

$failures = 0;

function _capture($fn) {{
    ob_start();
    $fn();
    return ob_get_clean();
}}

function _check($name, $actual, $expected) {{
    global $failures;
    if ($actual === $expected) {{
        echo "PASS: $name\\n";
    }} else {{
        $failures++;
        echo "FAIL: $name: expected " . var_export($expected, true) . ", got " . var_export($actual, true) . "\\n";
    }}
}}

{chr(10).join(checks)}

exit($failures > 0 ? 1 : 0);
'''


def generate_regression_test_file(language: str, chunk_results: list[dict]) -> str | None:
    """chunk_results: [{"modernized_code": str, "probes": [{"snippet",
    "baseline_stdout"}, ...]}, ...] — every SUCCESSFULLY modernized chunk
    from one source file that has at least one probe. Returns the
    generated test file's source code, or None if no chunk has any
    probes at all (nothing to persist) or the language isn't one of the
    4 that generate probes."""
    chunk_results = [c for c in chunk_results if c.get("probes")]
    if not chunk_results:
        return None
    if language == "python":
        return _generate_python_test(chunk_results)
    if language == "javascript":
        return _generate_js_test(chunk_results, typescript=False)
    if language == "typescript":
        return _generate_js_test(chunk_results, typescript=True)
    if language == "php":
        return _generate_php_test(chunk_results)
    return None
