"""Integration tests for the LangGraph wiring itself: retry loop,
escalation switching, risk-assessment hookup, and probe-check hookup.

Unlike tests/test_nodes.py (which tests each node function in isolation
with mocks), these run the REAL compiled graph via agents.graph.modernize()
end to end — real state transitions, real router decisions, real node
composition — with only the LLM and the sandbox verify() faked out. This
is what actually proves the pieces wire together correctly; the unit
tests only prove each piece works alone. No Docker or Ollama needed, so
this runs in CI.

Patch targets, and why: a function's global lookups always resolve
against the module it was DEFINED in, not the module that imported it.
refactorer_node/verifier_node/assess_risk/generate_probes are all defined
in agents.nodes, so patching agents.nodes.llm / agents.nodes.verify
covers all of them regardless of how agents.graph imported them. But
_capture_baseline_stdout, _capture_function_probes, and the assess_risk/
generate_probes CALL SITES inside modernize() are defined in agents.graph,
which did `from sandbox.verifier import verify` and `from agents.nodes
import ... assess_risk, generate_probes` — those bind local names in
agents.graph's own namespace, so THOSE call sites need agents.graph.verify
/ agents.graph.assess_risk / agents.graph.generate_probes patched
separately.
"""
import pytest
from unittest.mock import patch
from types import SimpleNamespace

from agents.graph import modernize


@pytest.fixture(autouse=True)
def _no_real_security_scan():
    """scan_security() makes a genuine Docker call (semgrep), unlike
    everything else in agents.graph.modernize() which either goes
    through the LLM (mocked via agents.nodes.llm in each test) or is
    explicitly mocked (agents.graph.verify). Without this, every test
    that reaches a "success" state would silently hit real Docker —
    exactly the dependency this whole file exists to avoid, confirmed
    by this fixture's own necessity: test runtime dropped from ~4s back
    to milliseconds once added. autouse so future tests get this for
    free instead of relying on each one to remember it individually."""
    with patch("agents.graph.scan_security", return_value=(False, [])):
        yield


@pytest.fixture(autouse=True)
def _no_real_mutation_check():
    """check_mutation_confidence() makes an EXTRA LLM call (generate_mutant)
    and an extra verify() call on top of everything else in
    agents.graph.modernize() — both against the same agents.nodes.llm/
    verify each test already mocks for the main graph flow, so this
    doesn't add a genuine Docker/Ollama dependency the way scan_security
    did, but it DOES silently add one more call to both, throwing off
    any test that asserts an exact call_count or relies on QueuedVerify's
    result ordering (confirmed: broke two pre-existing call-count
    assertions the moment this was wired in). autouse for the same
    reason as the fixtures above — isolated by default, dedicated tests
    below opt back in explicitly."""
    with patch("agents.graph.check_mutation_confidence", return_value=(False, "")):
        yield


@pytest.fixture(autouse=True)
def _single_candidate_by_default():
    """refactorer_node generates BEST_OF_N_ON_FIRST_ATTEMPT candidates on
    iteration 0 — by default 2, the second coming from _diversity_llm, a
    SEPARATE module-level instance that a test patching only agents.nodes.
    llm does not mock. Left alone, that second candidate is generated by
    a genuine, unmocked call to _diversity_llm on every single test that
    reaches iteration 0 (i.e. nearly all of them) — regardless of whether
    verifier_node ever ends up needing to check it, since generation
    happens unconditionally. That's a real, silent Ollama dependency in
    what's supposed to be a no-Ollama-needed test file; confirmed by two
    pre-existing tests that "passed" here only because Ollama happened to
    be running locally, and would hang or error in CI. Pinned to 1 by
    default so every test is isolated unless it explicitly opts back in
    (see the dedicated best-of-N tests below, which override this and
    mock _diversity_llm themselves)."""
    with patch("agents.nodes.BEST_OF_N_ON_FIRST_ATTEMPT", 1):
        yield


class ScriptedLLM:
    """Returns responses from a fixed list, in order, clamping to the
    last entry once exhausted — so a single-item list means "always
    return this," and a longer list scripts an exact call sequence."""

    def __init__(self, responses: list[str]):
        self.responses = responses
        self.calls: list[list] = []

    def invoke(self, messages):
        self.calls.append(messages)
        idx = min(len(self.calls) - 1, len(self.responses) - 1)
        return SimpleNamespace(content=self.responses[idx])

    @property
    def call_count(self) -> int:
        return len(self.calls)


class QueuedVerify:
    """Returns results from a fixed list, in order, clamping to the last
    entry once exhausted. Records every candidate source it was called
    with, for assertions."""

    def __init__(self, results: list[dict]):
        self.results = results
        self.calls: list[str] = []

    def __call__(self, source_code, filename, run_cmd, **kwargs):
        self.calls.append(source_code)
        idx = min(len(self.calls) - 1, len(self.results) - 1)
        return self.results[idx]

    @property
    def call_count(self) -> int:
        return len(self.calls)


_OK = {"status": "success", "stderr": "", "stdout": "ok\n", "exit_code": 0}
_FAIL = {"status": "failed", "stderr": "compile error: bad syntax", "stdout": "", "exit_code": 1}
_RISK_NO = "RISK: no\nPure function, no side effects."

_CPP_SOURCE = b"int add(int a, int b) { return a + b; }\n"


def test_happy_path_succeeds_on_first_attempt():
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",  # refactor attempt 1
        _RISK_NO,                                     # risk assessment
    ])
    fake_verify = QueuedVerify([_OK])  # baseline + verifier both "ok"

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5)

    assert final_state["status"] == "success"
    assert final_state["iteration_count"] == 1
    assert final_state["risk_flag"] is False


def test_retry_then_succeed_carries_error_into_second_attempt():
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a - b; }",  # attempt 1 (verify will fail it)
        "int add(int a, int b) { return a + b; }",  # attempt 2 (verify will pass it)
        _RISK_NO,
    ])
    fake_verify = QueuedVerify([_OK, _FAIL, _OK])  # baseline, attempt1 fail, attempt2 ok

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5)

    assert final_state["status"] == "success"
    assert final_state["iteration_count"] == 2
    # The second refactor call must have seen the first attempt's error —
    # this is the actual "does retry feed context back in" proof.
    second_call_text = str(fake_llm.calls[1])
    assert "compile error" in second_call_text


def test_gives_up_after_max_iterations():
    fake_llm = ScriptedLLM(["int add(int a, int b) { return a - b; }"])  # always wrong
    fake_verify = QueuedVerify([_OK, _FAIL])  # baseline ok, every verifier attempt fails

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=3)

    assert final_state["status"] == "gave_up"
    assert final_state["iteration_count"] == 3
    # gave_up means the fallback path ran, not a fluke of the loop
    # bottoming out some other way — no risk assessment should have run
    # since the chunk never succeeded.
    assert final_state["risk_flag"] is False


def test_escalates_to_stronger_model_after_threshold():
    base_llm = ScriptedLLM(["int add(int a, int b) { return a - b; }"])  # always wrong
    escalation_llm = ScriptedLLM(["int add(int a, int b) { return a + b; }"])  # gets it right
    fake_verify = QueuedVerify([_OK, _FAIL, _FAIL, _OK])  # baseline, 2 base failures, escalation success

    with patch("agents.nodes.llm", base_llm), \
         patch("agents.nodes.escalation_llm", escalation_llm), \
         patch("agents.nodes.ESCALATION_MODEL", "fake-strong-model"), \
         patch("agents.nodes.ESCALATION_THRESHOLD", 2), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5)

    assert final_state["status"] == "success"
    # base model tried exactly twice (iteration_count 0 and 1, both below
    # threshold 2), then escalation model took over and got it right on
    # its first attempt. base_llm gets ONE more call after that: the
    # winning candidate was written by escalation_llm, so assess_risk
    # deliberately reviews with the OTHER model (base) — a model doesn't
    # review its own output (see _select_reviewer_llm's docstring) — so
    # 3 total, not 2.
    assert base_llm.call_count == 3
    assert escalation_llm.call_count == 1


def test_risk_assessment_result_flows_into_final_state():
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",
        "RISK: yes\nThis touches a global counter.",
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5)

    assert final_state["status"] == "success"
    assert final_state["risk_flag"] is True
    assert "global counter" in final_state["risk_reason"]


def test_mutation_confidence_result_flows_into_final_state():
    # Mirrors test_risk_assessment_result_flows_into_final_state's
    # approach: fake the check itself (already unit-tested directly in
    # test_nodes.py) rather than re-deriving its internal LLM/verify call
    # sequence here — this test only proves the WIRING from
    # check_mutation_confidence's return value into final_state.
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",
        _RISK_NO,
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None), \
         patch("agents.graph.check_mutation_confidence", return_value=(True, "checks had no bite")):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5)

    assert final_state["status"] == "success"
    assert final_state["mutation_confidence_flag"] is True
    assert final_state["mutation_confidence_reason"] == "checks had no bite"


def test_mutation_confidence_not_run_when_chunk_fails():
    # Same "post-success only" cost discipline as risk/security checks —
    # no point mutating and re-verifying a chunk that never passed in
    # the first place.
    fake_llm = ScriptedLLM(["int add(int a, int b) { return a - b; }"])  # always wrong
    fake_verify = QueuedVerify([_OK, _FAIL])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None), \
         patch("agents.graph.check_mutation_confidence") as mock_mutation_check:
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=1)

    assert final_state["status"] == "gave_up"
    mock_mutation_check.assert_not_called()


def test_interactive_false_never_pauses_even_when_flagged():
    # Default behavior must stay completely unchanged: a flagged chunk
    # still comes back "success" with the flag set, exactly as before
    # this feature existed, unless interactive=True is explicitly passed.
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",
        "RISK: yes\nTouches global state.",
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize(
            "cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5, interactive=False,
        )

    assert final_state["status"] == "success"
    assert final_state["risk_flag"] is True
    assert final_state["review_thread_id"] is None


def test_interactive_true_pauses_on_flagged_chunk_and_resumes_on_approval():
    from agents.review_graph import resume_review

    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",
        "RISK: yes\nTouches global state.",
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize(
            "cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5, interactive=True,
        )

    assert final_state["status"] == "awaiting_review"
    assert final_state["risk_flag"] is True
    assert final_state["review_thread_id"] is not None

    resumed = resume_review(final_state["review_thread_id"], approved=True)
    assert resumed["status"] == "approved"


def test_interactive_true_still_completes_normally_when_nothing_flagged():
    # An unflagged chunk in interactive mode must NOT pause at all — the
    # review graph auto-approves without ever calling interrupt() when
    # no flag is set (see review_graph.py's _review_node).
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",
        _RISK_NO,
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize(
            "cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5, interactive=True,
        )

    assert final_state["status"] == "success"
    assert final_state["review_thread_id"] is None


def test_probe_mismatch_fails_even_when_whole_file_check_passes():
    # This is the actual value proposition of the probe feature: a
    # function the file's own entry point never calls gets zero coverage
    # from the whole-file baseline check. Only the probe catches it.
    python_source = b"def add(a, b):\n    return a + b\n"

    fake_llm = ScriptedLLM([
        "def add(a, b):\n    return a - b",  # WRONG — subtracts instead
    ])

    def fake_generate_probes(language, function_code, count=3):
        return ["print(add(2, 3))"]

    # Sequence inside modernize(): baseline call, probe-baseline call
    # (no real call sites exist in this tiny source, so it falls straight
    # to the synthesized probe), then verifier_node's whole-file call +
    # probe call. The probe mismatches here, so verifier_node returns
    # immediately WITHOUT reaching the determinism re-check (that only
    # runs when a probe matches its baseline) — 4 calls total, not 5.
    fake_verify = QueuedVerify([
        _OK,                                                     # whole-file baseline
        {"status": "success", "stderr": "", "stdout": "5\n", "exit_code": 0},  # probe baseline: 2+3=5
        _OK,                                                     # attempt1 whole-file check (passes — file still runs)
        {"status": "success", "stderr": "", "stdout": "-1\n", "exit_code": 0},  # attempt1 probe: 2-3=-1, MISMATCH
    ])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.graph.generate_probes", fake_generate_probes), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize("python", python_source, 0, len(python_source.rstrip(b"\n")), max_iterations=1)

    assert final_state["status"] == "gave_up"
    assert "different result" in final_state["compiler_stderr"]


def test_security_scan_result_flows_into_final_state():
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",
        _RISK_NO,
    ])
    fake_verify = QueuedVerify([_OK])
    fake_findings = [{"rule_id": "sandbox.cpp-system-call", "line": 3, "message": "system() is dangerous"}]

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.graph.scan_security", return_value=(True, fake_findings)), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5)

    assert final_state["status"] == "success"  # flags, does not block
    assert final_state["security_flag"] is True
    assert final_state["security_findings"] == fake_findings


def test_security_scan_skipped_when_chunk_never_succeeds():
    fake_llm = ScriptedLLM(["int add(int a, int b) { return a - b; }"])  # always wrong
    fake_verify = QueuedVerify([_OK, _FAIL])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.graph.scan_security") as mock_scan, \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=2)

    assert final_state["status"] == "gave_up"
    mock_scan.assert_not_called()  # no point scanning a rejected change


def test_best_of_n_succeeds_via_second_candidate_without_a_full_retry():
    # Candidate 0 (deterministic, temperature=0) is wrong; candidate 1
    # (from _diversity_llm) happens to be right. This should succeed
    # WITHOUT ever incrementing to a second graph iteration — both
    # candidates are tried within the SAME refactorer+verifier round trip,
    # which is the entire point of trying more than one guess up front
    # instead of only finding out one is wrong after committing to it.
    base_llm = ScriptedLLM(["int add(int a, int b) { return a - b; }"])  # wrong
    diverse_llm = ScriptedLLM(["int add(int a, int b) { return a + b; }"])  # right
    fake_verify = QueuedVerify([_OK, _FAIL, _OK])  # baseline, candidate0 fail, candidate1 ok

    with patch("agents.nodes.llm", base_llm), \
         patch("agents.nodes._diversity_llm", diverse_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None), \
         patch("agents.nodes.BEST_OF_N_ON_FIRST_ATTEMPT", 2):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5)

    assert final_state["status"] == "success"
    assert final_state["iteration_count"] == 1  # both candidates tried in ONE round trip
    assert final_state["modernized_code"] == "int add(int a, int b) { return a + b; }"
    # base_llm: 1 call generating candidate 0, + 1 more for post-success
    # risk assessment (which always uses the base model — see
    # assess_risk's docstring). diverse_llm: exactly 1, for candidate 1.
    assert base_llm.call_count == 2
    assert diverse_llm.call_count == 1


def test_best_of_n_reports_first_candidates_error_when_all_fail():
    base_llm = ScriptedLLM(["int add(int a, int b) { return a - b; }"])  # wrong, distinctly
    diverse_llm = ScriptedLLM(["int add(int a, int b) { return a * b; }"])  # also wrong
    fake_verify = QueuedVerify([
        _OK,
        {"status": "failed", "stderr": "candidate0 error", "stdout": "", "exit_code": 1},
        {"status": "failed", "stderr": "candidate1 error", "stdout": "", "exit_code": 1},
    ])

    with patch("agents.nodes.llm", base_llm), \
         patch("agents.nodes._diversity_llm", diverse_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None), \
         patch("agents.nodes.BEST_OF_N_ON_FIRST_ATTEMPT", 2):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=1)

    assert final_state["status"] == "gave_up"
    # The FIX prompt on the (nonexistent, since max_iterations=1 here)
    # next retry would see candidate0's error specifically — an
    # arbitrary but consistent choice among N failures.
    assert "candidate0 error" in final_state["compiler_stderr"]


def test_punt_check_skips_chunk_before_any_attempt():
    fake_llm = ScriptedLLM(["PUNT: yes\nToo risky, relies on unclear legacy semantics."])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize(
            "cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")),
            max_iterations=5, punt_check_enabled=True,
        )

    assert final_state["status"] == "gave_up"
    assert final_state["punted"] is True
    assert final_state["iteration_count"] == 0
    assert "Too risky" in final_state["compiler_stderr"]
    # The punt check itself is the ONLY LLM call — no refactor attempt,
    # no risk assessment (post-success only), and NO verify() call at
    # all (not even baseline capture) since it short-circuits first.
    assert fake_llm.call_count == 1
    assert fake_verify.call_count == 0


def test_punt_check_disabled_by_default_even_with_a_punt_worthy_response():
    # punt_check_enabled defaults to False — a model that WOULD punt if
    # asked must have no effect when the check is simply never run,
    # confirming this feature is fully opt-in with zero behavior change
    # otherwise (assess_punt is never called, so its "PUNT: yes" script
    # entry here is never even reached).
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",  # refactor attempt 1
        _RISK_NO,                                     # risk assessment
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5)

    assert final_state["status"] == "success"
    assert final_state["punted"] is False


def test_punt_check_false_negative_proceeds_to_normal_attempt():
    fake_llm = ScriptedLLM([
        "PUNT: no\nConfident about this one.",
        "int add(int a, int b) { return a + b; }",  # refactor attempt 1
        _RISK_NO,                                     # risk assessment
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize(
            "cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")),
            max_iterations=5, punt_check_enabled=True,
        )

    assert final_state["status"] == "success"
    assert final_state["punted"] is False


def test_context_signatures_populated_and_reach_the_refactor_prompt():
    multi_fn_source = b"int add(int a, int b) { return a + b; }\nint sub(int a, int b) { return a - b; }\n"
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",  # refactor attempt 1
        _RISK_NO,                                     # risk assessment
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None):
        final_state = modernize("cpp", multi_fn_source, 0, len("int add(int a, int b) { return a + b; }"), max_iterations=5)

    assert final_state["status"] == "success"
    assert final_state["context_signatures"] == ["int sub(int a, int b) { return a - b; }"]
    refactor_human_message = fake_llm.calls[0][1]
    assert "int sub(int a, int b) { return a - b; }" in refactor_human_message.content


def test_referenced_type_definitions_populated_and_reach_the_refactor_prompt():
    full_source = (
        b"class ConfigError(Exception):\n    pass\n\n"
        b"def load_config(path):\n    raise ConfigError('bad')\n"
    )
    fake_llm = ScriptedLLM([
        "def load_config(path):\n    raise ConfigError('bad')",  # refactor attempt 1
        _RISK_NO,                                                  # risk assessment
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.graph.generate_probes", return_value=[]), \
         patch("agents.nodes.escalation_llm", None):
        chunk_start = full_source.index(b"def load_config")
        chunk_end = chunk_start + len(b"def load_config(path):\n    raise ConfigError('bad')")
        final_state = modernize("python", full_source, chunk_start, chunk_end, max_iterations=5)

    assert final_state["status"] == "success"
    assert len(final_state["referenced_type_definitions"]) == 1
    assert "class ConfigError(Exception):" in final_state["referenced_type_definitions"][0]
    # And it actually reached the refactor prompt, not just the state.
    refactor_human_message = fake_llm.calls[0][1]
    assert "class ConfigError(Exception):" in refactor_human_message.content


def test_exemplar_retrieved_and_reaches_prompt_when_embeddings_enabled():
    exemplar = {"original": "def old(a, b): return a+b", "modernized": "def old(a: int, b: int) -> int: return a+b"}
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",  # refactor attempt 1
        _RISK_NO,                                     # risk assessment
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None), \
         patch("agents.graph.exemplar_bank.find_best_exemplar", return_value=exemplar) as mock_find, \
         patch("agents.graph.exemplar_bank.record") as mock_record:
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5)

    mock_find.assert_called_once()
    assert final_state["exemplar_original"] == exemplar["original"]
    assert final_state["exemplar_modernized"] == exemplar["modernized"]
    refactor_human_message = fake_llm.calls[0][1]
    assert exemplar["original"] in refactor_human_message.content
    assert exemplar["modernized"] in refactor_human_message.content
    # A clean success (no risk/security/low-confidence flag) must be
    # recorded as a NEW exemplar for future runs.
    mock_record.assert_called_once()


def test_exemplar_not_recorded_when_risk_flagged():
    fake_llm = ScriptedLLM([
        "int add(int a, int b) { return a + b; }",  # refactor attempt 1
        "RISK: yes\nTouches global state.",           # risk assessment — flagged
    ])
    fake_verify = QueuedVerify([_OK])

    with patch("agents.nodes.llm", fake_llm), \
         patch("agents.nodes.verify", fake_verify), \
         patch("agents.graph.verify", fake_verify), \
         patch("agents.nodes.escalation_llm", None), \
         patch("agents.graph.exemplar_bank.find_best_exemplar", return_value=None), \
         patch("agents.graph.exemplar_bank.record") as mock_record:
        final_state = modernize("cpp", _CPP_SOURCE, 0, len(_CPP_SOURCE.rstrip(b"\n")), max_iterations=5)

    assert final_state["status"] == "success"
    assert final_state["risk_flag"] is True
    mock_record.assert_not_called()
